from .llm_config import LLMConfig
from .tts_config import TTSConfig


class Config:
    """
    Centralized configuration access for LLM and TTS configurations.
    Provides direct access to all critical attributes from LLMConfig and TTSConfig.
    """
    LLM_CONFIG = LLMConfig.get_instance()
    TTS_CONFIG = TTSConfig.get_instance()

    # Expose LLMConfig attributes
    OPENAI_API_KEY = LLM_CONFIG.OPENAI_API_KEY
    OPENAI_RESPONSE_MODEL = LLM_CONFIG.OPENAI_RESPONSE_MODEL
    OPENAI_TEMPERATURE = LLM_CONFIG.OPENAI_TEMPERATURE
    OPENAI_TOP_P = LLM_CONFIG.OPENAI_TOP_P
    OPENAI_N = LLM_CONFIG.OPENAI_N
    OPENAI_SYSTEM_PROMPT = LLM_CONFIG.OPENAI_SYSTEM_PROMPT
    OPENAI_STREAM_OPTIONS = LLM_CONFIG.OPENAI_STREAM_OPTIONS
    OPENAI_MAX_TOKENS = LLM_CONFIG.OPENAI_MAX_TOKENS
    OPENAI_PRESENCE_PENALTY = LLM_CONFIG.OPENAI_PRESENCE_PENALTY
    OPENAI_FREQUENCY_PENALTY = LLM_CONFIG.OPENAI_FREQUENCY_PENALTY

    ANTHROPIC_API_KEY = LLM_CONFIG.ANTHROPIC_API_KEY
    ANTHROPIC_RESPONSE_MODEL = LLM_CONFIG.ANTHROPIC_RESPONSE_MODEL
    ANTHROPIC_TEMPERATURE = LLM_CONFIG.ANTHROPIC_TEMPERATURE
    ANTHROPIC_TOP_P = LLM_CONFIG.ANTHROPIC_TOP_P
    ANTHROPIC_SYSTEM_PROMPT = LLM_CONFIG.ANTHROPIC_SYSTEM_PROMPT
    ANTHROPIC_MAX_TOKENS = LLM_CONFIG.ANTHROPIC_MAX_TOKENS
    ANTHROPIC_STREAM_OPTIONS = LLM_CONFIG.ANTHROPIC_STREAM_OPTIONS
    ANTHROPIC_STOP_SEQUENCES = LLM_CONFIG.ANTHROPIC_STOP_SEQUENCES

    GEMINI_API_KEY = LLM_CONFIG.GEMINI_API_KEY
    GEMINI_MODEL_VERSION = LLM_CONFIG.GEMINI_MODEL_VERSION
    GEMINI_TEMPERATURE = LLM_CONFIG.GEMINI_TEMPERATURE
    GEMINI_SYSTEM_PROMPT = LLM_CONFIG.GEMINI_SYSTEM_PROMPT
    GEMINI_MAX_OUTPUT_TOKENS = LLM_CONFIG.GEMINI_MAX_OUTPUT_TOKENS
    GEMINI_TOP_P = LLM_CONFIG.GEMINI_TOP_P
    GEMINI_CANDIDATE_COUNT = LLM_CONFIG.GEMINI_CANDIDATE_COUNT

    # Expose TTSConfig attributes directly
    TTS_PROVIDER = TTS_CONFIG.TTS_PROVIDER
    MODULES = TTS_CONFIG.MODULES
    USE_PHRASE_SEGMENTATION = TTS_CONFIG.USE_PHRASE_SEGMENTATION
    DELIMITERS = TTS_CONFIG.DELIMITERS
    TOKENIZER_TYPE = TTS_CONFIG.TOKENIZER_TYPE
    NLTK_CONFIG = TTS_CONFIG.NLTK_CONFIG
    STANZA_CONFIG = TTS_CONFIG.STANZA_CONFIG
    CUSTOM_TEXT_MODIFIER_ENABLED = TTS_CONFIG.CUSTOM_TEXT_MODIFIER_ENABLED

    # OpenAI TTS Configurations
    OPENAI_TTS_CHUNK_SIZE = TTS_CONFIG.OPENAI_TTS_CHUNK_SIZE
    OPENAI_TTS_SPEED = TTS_CONFIG.OPENAI_TTS_SPEED
    OPENAI_TTS_VOICE = TTS_CONFIG.OPENAI_TTS_VOICE
    OPENAI_TTS_MODEL = TTS_CONFIG.OPENAI_TTS_MODEL
    OPENAI_AUDIO_FORMAT = TTS_CONFIG.OPENAI_AUDIO_FORMAT
    OPENAI_AUDIO_FORMAT_RATES = TTS_CONFIG.OPENAI_AUDIO_FORMAT_RATES
    OPENAI_PLAYBACK_RATE = TTS_CONFIG.OPENAI_PLAYBACK_RATE

    # OpenAI TTS Configurations
    OPENAI_TTS_CHUNK_SIZE = TTS_CONFIG.OPENAI_TTS_CHUNK_SIZE
    OPENAI_TTS_SPEED = TTS_CONFIG.OPENAI_TTS_SPEED
    OPENAI_TTS_VOICE = TTS_CONFIG.OPENAI_TTS_VOICE
    OPENAI_TTS_MODEL = TTS_CONFIG.OPENAI_TTS_MODEL
    OPENAI_AUDIO_FORMAT = TTS_CONFIG.OPENAI_AUDIO_FORMAT
    OPENAI_AUDIO_FORMAT_RATES = TTS_CONFIG.OPENAI_AUDIO_FORMAT_RATES
    OPENAI_PLAYBACK_RATE = TTS_CONFIG.OPENAI_PLAYBACK_RATE

    # Azure TTS Configurations
    AZURE_TTS_SPEED = TTS_CONFIG.AZURE_TTS_SPEED
    AZURE_TTS_VOICE = TTS_CONFIG.AZURE_TTS_VOICE
    AZURE_AUDIO_FORMAT = TTS_CONFIG.AZURE_AUDIO_FORMAT
    AZURE_AUDIO_FORMAT_RATES = TTS_CONFIG.AZURE_AUDIO_FORMAT_RATES
    AZURE_PLAYBACK_RATE = TTS_CONFIG.AZURE_PLAYBACK_RATE
    AZURE_ENABLE_PROFANITY_FILTER = TTS_CONFIG.AZURE_ENABLE_PROFANITY_FILTER
    AZURE_STABILITY = TTS_CONFIG.AZURE_STABILITY
    AZURE_PROSODY = TTS_CONFIG.AZURE_PROSODY

    # Expose Azure API Keys and Region
    AZURE_SPEECH_KEY = TTS_CONFIG.AZURE_SPEECH_KEY
    AZURE_SPEECH_REGION = TTS_CONFIG.AZURE_SPEECH_REGION


    # Audio Playback Configuration
    AUDIO_FORMAT = TTS_CONFIG.AUDIO_FORMAT
    AUDIO_CHANNELS = TTS_CONFIG.AUDIO_CHANNELS
    AUDIO_RATE = TTS_CONFIG.AUDIO_RATE
