from .llm_config import LLMConfig
from .tts_config import TTSConfig


class Config:
    """
    Centralized configuration access for LLM and TTS configurations.
    Provides direct access to all critical attributes from LLMConfig and TTSConfig.
    """
    LLM_CONFIG = LLMConfig.get_instance()
    TTS_CONFIG = TTSConfig.get_instance()

    # Expose LLMConfig attributes
    OPENAI_API_KEY = LLM_CONFIG.OPENAI_API_KEY
    OPENAI_RESPONSE_MODEL = LLM_CONFIG.OPENAI_RESPONSE_MODEL
    OPENAI_TEMPERATURE = LLM_CONFIG.OPENAI_TEMPERATURE
    OPENAI_TOP_P = LLM_CONFIG.OPENAI_TOP_P
    OPENAI_N = LLM_CONFIG.OPENAI_N
    OPENAI_SYSTEM_PROMPT = LLM_CONFIG.OPENAI_SYSTEM_PROMPT
    OPENAI_STREAM_OPTIONS = LLM_CONFIG.OPENAI_STREAM_OPTIONS
    OPENAI_MAX_TOKENS = LLM_CONFIG.OPENAI_MAX_TOKENS
    OPENAI_PRESENCE_PENALTY = LLM_CONFIG.OPENAI_PRESENCE_PENALTY
    OPENAI_FREQUENCY_PENALTY = LLM_CONFIG.OPENAI_FREQUENCY_PENALTY

    ANTHROPIC_API_KEY = LLM_CONFIG.ANTHROPIC_API_KEY
    ANTHROPIC_RESPONSE_MODEL = LLM_CONFIG.ANTHROPIC_RESPONSE_MODEL
    ANTHROPIC_TEMPERATURE = LLM_CONFIG.ANTHROPIC_TEMPERATURE
    ANTHROPIC_TOP_P = LLM_CONFIG.ANTHROPIC_TOP_P
    ANTHROPIC_SYSTEM_PROMPT = LLM_CONFIG.ANTHROPIC_SYSTEM_PROMPT
    ANTHROPIC_MAX_TOKENS = LLM_CONFIG.ANTHROPIC_MAX_TOKENS
    ANTHROPIC_STREAM_OPTIONS = LLM_CONFIG.ANTHROPIC_STREAM_OPTIONS
    ANTHROPIC_STOP_SEQUENCES = LLM_CONFIG.ANTHROPIC_STOP_SEQUENCES

    GEMINI_API_KEY = LLM_CONFIG.GEMINI_API_KEY
    GEMINI_MODEL_VERSION = LLM_CONFIG.GEMINI_MODEL_VERSION
    GEMINI_TEMPERATURE = LLM_CONFIG.GEMINI_TEMPERATURE
    GEMINI_SYSTEM_PROMPT = LLM_CONFIG.GEMINI_SYSTEM_PROMPT
    GEMINI_MAX_OUTPUT_TOKENS = LLM_CONFIG.GEMINI_MAX_OUTPUT_TOKENS
    GEMINI_TOP_P = LLM_CONFIG.GEMINI_TOP_P
    GEMINI_CANDIDATE_COUNT = LLM_CONFIG.GEMINI_CANDIDATE_COUNT

    MISTRAL_API_KEY = LLM_CONFIG.MISTRAL_API_KEY
    MISTRAL_RESPONSE_MODEL = LLM_CONFIG.MISTRAL_RESPONSE_MODEL
    MISTRAL_TEMPERATURE = LLM_CONFIG.MISTRAL_TEMPERATURE
    MISTRAL_TOP_P = LLM_CONFIG.MISTRAL_TOP_P
    MISTRAL_SYSTEM_PROMPT = LLM_CONFIG.MISTRAL_SYSTEM_PROMPT
    MISTRAL_MAX_TOKENS = LLM_CONFIG.MISTRAL_MAX_TOKENS
    MISTRAL_STOP_SEQUENCES = LLM_CONFIG.MISTRAL_STOP_SEQUENCES
    MISTRAL_STREAM_OPTIONS = LLM_CONFIG.MISTRAL_STREAM_OPTIONS

    GROK_API_KEY = LLM_CONFIG.GROK_API_KEY
    GROK_API_BASE = LLM_CONFIG.GROK_API_BASE
    GROK_RESPONSE_MODEL = LLM_CONFIG.GROK_RESPONSE_MODEL
    GROK_TEMPERATURE = LLM_CONFIG.GROK_TEMPERATURE
    GROK_TOP_P = LLM_CONFIG.GROK_TOP_P
    GROK_SYSTEM_PROMPT = LLM_CONFIG.GROK_SYSTEM_PROMPT
    GROK_MAX_TOKENS = LLM_CONFIG.GROK_MAX_TOKENS
    GROK_STREAM_OPTIONS = LLM_CONFIG.GROK_STREAM_OPTIONS
    GROK_STOP = LLM_CONFIG.GROK_STOP

    DEEPINFRA_API_KEY = LLM_CONFIG.DEEPINFRA_API_KEY
    DEEPINFRA_API_BASE = LLM_CONFIG.DEEPINFRA_API_BASE
    DEEPINFRA_RESPONSE_MODEL = LLM_CONFIG.DEEPINFRA_RESPONSE_MODEL
    DEEPINFRA_TEMPERATURE = LLM_CONFIG.DEEPINFRA_TEMPERATURE
    DEEPINFRA_TOP_P = LLM_CONFIG.DEEPINFRA_TOP_P
    DEEPINFRA_N = LLM_CONFIG.DEEPINFRA_N
    DEEPINFRA_MAX_TOKENS = LLM_CONFIG.DEEPINFRA_MAX_TOKENS
    DEEPINFRA_PRESENCE_PENALTY = LLM_CONFIG.DEEPINFRA_PRESENCE_PENALTY
    DEEPINFRA_FREQUENCY_PENALTY = LLM_CONFIG.DEEPINFRA_FREQUENCY_PENALTY
    DEEPINFRA_LOGIT_BIAS = LLM_CONFIG.DEEPINFRA_LOGIT_BIAS
    DEEPINFRA_USER = LLM_CONFIG.DEEPINFRA_USER
    DEEPINFRA_STOP = LLM_CONFIG.DEEPINFRA_STOP
    DEEPINFRA_SYSTEM_PROMPT = LLM_CONFIG.DEEPINFRA_SYSTEM_PROMPT
    DEEPINFRA_STREAM_OPTIONS = LLM_CONFIG.DEEPINFRA_STREAM_OPTIONS

    OPENROUTER_API_KEY = LLM_CONFIG.OPENROUTER_API_KEY
    OPENROUTER_API_BASE = LLM_CONFIG.OPENROUTER_API_BASE
    OPENROUTER_RESPONSE_MODEL = LLM_CONFIG.OPENROUTER_RESPONSE_MODEL
    OPENROUTER_TEMPERATURE = LLM_CONFIG.OPENROUTER_TEMPERATURE
    OPENROUTER_TOP_P = LLM_CONFIG.OPENROUTER_TOP_P
    OPENROUTER_N = LLM_CONFIG.OPENROUTER_N
    OPENROUTER_MAX_TOKENS = LLM_CONFIG.OPENROUTER_MAX_TOKENS
    OPENROUTER_PRESENCE_PENALTY = LLM_CONFIG.OPENROUTER_PRESENCE_PENALTY
    OPENROUTER_FREQUENCY_PENALTY = LLM_CONFIG.OPENROUTER_FREQUENCY_PENALTY
    OPENROUTER_LOGIT_BIAS = LLM_CONFIG.OPENROUTER_LOGIT_BIAS
    OPENROUTER_USER = LLM_CONFIG.OPENROUTER_USER
    OPENROUTER_STOP = LLM_CONFIG.OPENROUTER_STOP
    OPENROUTER_SYSTEM_PROMPT = LLM_CONFIG.OPENROUTER_SYSTEM_PROMPT
    OPENROUTER_STREAM_OPTIONS = LLM_CONFIG.OPENROUTER_STREAM_OPTIONS
    OPENROUTER_MODALITIES = LLM_CONFIG.OPENROUTER_MODALITIES

    # Expose TTSConfig attributes directly
    TTS_PROVIDER = TTS_CONFIG.TTS_PROVIDER
    USE_SEGMENTATION = TTS_CONFIG.USE_SEGMENTATION
    DELIMITERS = TTS_CONFIG.DELIMITERS
    NLP_MODULE = TTS_CONFIG.NLP_MODULE
    CHARACTER_MAXIMUM = TTS_CONFIG.CHARACTER_MAXIMUM

    # OpenAI TTS Configurations
    OPENAI_TTS_CHUNK_SIZE = TTS_CONFIG.OPENAI_TTS_CHUNK_SIZE
    OPENAI_TTS_SPEED = TTS_CONFIG.OPENAI_TTS_SPEED
    OPENAI_TTS_VOICE = TTS_CONFIG.OPENAI_TTS_VOICE
    OPENAI_TTS_MODEL = TTS_CONFIG.OPENAI_TTS_MODEL
    OPENAI_AUDIO_FORMAT = TTS_CONFIG.OPENAI_AUDIO_FORMAT
    OPENAI_AUDIO_FORMAT_RATES = TTS_CONFIG.OPENAI_AUDIO_FORMAT_RATES
    OPENAI_PLAYBACK_RATE = TTS_CONFIG.OPENAI_PLAYBACK_RATE

    # Azure TTS Configurations
    AZURE_TTS_SPEED = TTS_CONFIG.AZURE_TTS_SPEED
    AZURE_TTS_VOICE = TTS_CONFIG.AZURE_TTS_VOICE
    AZURE_AUDIO_FORMAT = TTS_CONFIG.AZURE_AUDIO_FORMAT
    AZURE_AUDIO_FORMAT_RATES = TTS_CONFIG.AZURE_AUDIO_FORMAT_RATES
    AZURE_PLAYBACK_RATE = TTS_CONFIG.AZURE_PLAYBACK_RATE
    AZURE_ENABLE_PROFANITY_FILTER = TTS_CONFIG.AZURE_ENABLE_PROFANITY_FILTER
    AZURE_STABILITY = TTS_CONFIG.AZURE_STABILITY
    AZURE_PROSODY = TTS_CONFIG.AZURE_PROSODY

    # Expose Azure API Keys and Region
    AZURE_SPEECH_KEY = TTS_CONFIG.AZURE_SPEECH_KEY
    AZURE_SPEECH_REGION = TTS_CONFIG.AZURE_SPEECH_REGION

    # Audio Playback Configuration
    AUDIO_FORMAT = TTS_CONFIG.AUDIO_FORMAT
    AUDIO_CHANNELS = TTS_CONFIG.AUDIO_CHANNELS
    AUDIO_RATE = TTS_CONFIG.AUDIO_RATE
